name: Code Review Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  code-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint code
        run: |
          echo "Linting code..."
          npm run lint
          echo "Linting completed successfully"

      - name: Analyze code quality
        run: |
          echo "Analyzing code quality..."
          npm run analyze
          echo "Code quality analysis completed"

      - name: Scan for vulnerabilities
        run: |
          echo "Scanning for security vulnerabilities..."
          npm audit
          echo "Vulnerability scanning completed"

      - name: Provide code review feedback
        run: |
          echo "Code review feedback:"
          echo "Linting results:"
          cat lint-results.txt
          echo "Code quality analysis results:"
          cat code-quality-results.txt
          echo "Security vulnerabilities:"
          cat security-scan-results.txt  
          
      - name: Enforce checks for merge
        if: github.event_name == 'pull_request'
        run: |
          echo "Enforcing required checks..."
          echo "All required checks passed, ready for merge"
