name: Dependency Updates

on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  check-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Update dependencies
        run: npm update

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies'
          branch: dependency-updates
          title: 'chore: update dependencies'
          body: 'This PR updates project dependencies.'
